config/routes.rb
Rails.application.routes.draw do
  resources :slides

  get 'appointments/list'
  get 'appointments/showcase'
  get 'appointments/help'
  resources :appointments

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'appointments#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/slide.rb
class Slide < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>"}, :default_url => "missing.png"
  validates_attachment :image, content_type: { content_type: [ "image/jpg", "image/jpeg", "image/png", "image/gif" ] }
  validates :image, presence: true
end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
  before_action :set_slide, only: [:show, :edit, :update, :destroy]

  # GET /slides
  # GET /slides.json
  def index
    @slides = Slide.all.order(created_at: :desc).paginate(:page => params[:page], :per_page => 8)
  end

  # GET /slides/1
  # GET /slides/1.json
  def show
  end

  # GET /slides/new
  def new
    @slide = Slide.new
  end

  # GET /slides/1/edit
  def edit
  end

  # POST /slides
  # POST /slides.json
  def create
    @slide = Slide.new(slide_params)

    respond_to do |format|
      if @slide.save
        format.html { redirect_to @slide, notice: t('.success') }
        format.json { render :show, status: :created, location: @slide }
      else
        format.html { render :new }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slides/1
  # PATCH/PUT /slides/1.json
  def update
    respond_to do |format|
      if @slide.update(slide_params)
        format.html { redirect_to @slide, notice: t('.success') }
        format.json { render :show, status: :ok, location: @slide }
      else
        format.html { render :edit }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slides/1
  # DELETE /slides/1.json
  def destroy
    @slide.destroy
    respond_to do |format|
      format.html { redirect_to slides_url, notice: t('.success') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slide
      @slide = Slide.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slide_params
      params.require(:slide).permit(:showcasable, :image)
    end
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/views/slides/_form.html.erb
<%= form_for(@slide) do |f| %>
<% if @slide.errors.any? %>
<div id="error_explanation">
  <h2><%= t('errors.template.header', model: t('activerecord.models.slide'), count: @slide.errors.count) %></h2>
  <ul>
    <% @slide.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="form-group">
  <div class="row">
    <div class="col-xs-3 col-md-3">
      <%= f.label :showcasable, t('.showcasable') %>
    </div>
    <div class="col-xs-9 col-md-9">
      <%= f.check_box :showcasable %>
    </div>
  </div>
</div>
<div class="form-group">
  <div class="row">
    <div class="col-xs-3 col-md-3">
      <%= f.label :image, t('.image') %>
    </div>
    <div class="col-xs-9 col-md-9">
      <%= f.file_field :image, class: "form-control" %>
    </div>
  </div>
</div>

<div class="form-group">
  <%= f.submit t('.submit'), class: "btn btn-primary" %>
</div>
<% end %>

app/views/slides/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h2><%= t('.heading') %></h2>
  </div> <!-- /.panel-heading -->

  <div class="panel-body">
    <%= render 'form' %>
  </div> <!-- /.panel-body -->

  <div class="panel-footer">
    <%= link_to t('.show'), @slide %> |
    <%= link_to t('.back'), :back %>
  </div> <!-- /.panel-footer -->
</div> <!-- /.panel panel-default -->

app/views/slides/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h2><%= t('.heading') %></h2>
  </div> <!-- /.panel-heading -->

  <div class="panel-body">

    <div id="slides" class="js-masonry">
      <% @slides.each do |slide| %>
        <div class="box panel panel-default">
          <% if !slide.showcasable? %>
            <div class="hero-unit">
          <% end %>
          <div id="slides.slide">
            <%= link_to image_tag(slide.image.url(:medium), class: "img-responsive"), slide %>
          </div>
          <% if !slide.showcasable? %>
            </div>
          <% end %>
          <div class="panel-body">
            <div class="actions">
              <%= link_to t('.edit'), edit_slide_path(slide) %> | 
              <%= link_to t('.destroy'), slide, method: :delete, data: { confirm: t('.confirm') }  %>
            </div>
          </div> <!-- ./panel-body -->
        </div> <!-- ./panel-default -->
      <% end %>
    </div>

    <div class="center">
       <%= will_paginate @slides, renderer: BootstrapPagination::Rails %>
    </div>

  </div>
<div class="panel-footer">
    <%= link_to t('.new_slide'), new_slide_path %>
  </div> <!-- /.panel-footer -->
</div> <!-- /.panel panel-default -->

app/views/slides/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h2><%= t('.heading') %></h2>
  </div> <!-- /.panel-heading -->

  <div class="panel-body">
    <%= render 'form' %>
  </div> <!-- /.panel-body -->

  <div class="panel-footer">
    <%= link_to t('.back'), :back %>
  </div> <!-- /.panel-footer -->
</div> <!-- /.panel panel-default -->

app/views/slides/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h2><%= t('.heading') %></h2>
  </div> <!-- /.panel-heading -->

  <div class="panel-body">
    <div class="row">
      <div class="col-xs-6 col-md-3">
        <strong><%= t('.showcasable') %>:</strong>
      </div>
      <div class="col-xs-6 col-md-9">
        <%= @slide.showcasable %>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-6 col-md-3">
        <strong><%= t('.image') %>:</strong>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-md-12">
        <%= image_tag(@slide.image.url, class: "img-responsive") %>
      </div>
    </div>
   </div> <!-- /.panel-body -->

   <div class="panel-footer">
    <%= link_to t('.edit'), edit_slide_path(@slide) %> |
    <%= link_to t('.back'), :back %>
   </div> <!-- /.panel-footer -->
 </div> <!-- /.panel panel-default -->