config/routes.rb
Rails.application.routes.draw do
  resources :slides

  get 'appointments/list'
  get 'appointments/showcase'
  get 'appointments/help'
  resources :appointments

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'appointments#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  include Timeable
  validates :begin_date, :begin_time, :external_participant_salutation, :external_participant_name, presence: true
  validates :external_participant_title, length: { maximum: 10 }
  validates :external_participant_name, :external_participant_company, :clear_group_employee_name, length: { maximum: 50 }
  validate :validate_conditional_employee_salutation
  validate :validate_conditional_employee_name

  # Defines boundaries within a appointment begin has to be, compared to +Time.now+, to be qualified for displaying.
  #
  # ==== Examples:
  #
  # If the appointment has not yet begun, then the appointment will be displayed, if the begin is 30 minutes or less to +Time.now+
  # If the appointment has already begun, then the appointment will be displayed, if the begin was 15 minutes or less from +Time.now+
  BOUNDARIES = { begin_before: 30, begin_after: 15 }

  # Returns a list of all appointments ordered descending by begin_date and begin_time.
  def self.all_desc
    @appointments = Appointment.all
    @appointments_list = @appointments.order(begin_date: :desc, begin_time: :desc)
  end

  # Returns a list of appointments to be displayed in the showcase.
  def self.all_showcase
    # Get all appointments
    @appointments = Appointment.all
    # Order the liste of appointments ascending by begin_date and begin_time
    @appointments_asc = @appointments.order(:begin_date, :begin_time)
    # Create an array of todays appointments
    @appointments_today = []
    # Iterate over the ordered appointment list
    @appointments_asc.each do |appointment|
      # If the appointment is today, push it to the list of todays appointments
      if appointment.begin_date.today?
        @appointments_today.push appointment
      end
    end
    # If the resulting list of todays appointments has less or equal to 5 entries return the complete list
    if @appointments_today.size <= 5
      return @appointments_today
    else
      # Iterate over the list of todays appointments
      (0...@appointments_today.size).each do |i|
        # As long as there are more than 5 appointments in the list
        until @appointments_today.size <= 5 do
          # Get the current appointment
          appointment_today = @appointments_today[i]
          # If the appointment begin_time has expired (read: 15 minutes after Time.now)
          if (appointment_today.time_after_now?(appointment_today.begin_time)) && (appointment_today.difference_in_minutes(Time.now, appointment_today.begin_time) > BOUNDARIES[:begin_after])
            # Remove the appointment from the list
            @appointments_today.delete(appointment_today)
          end
        end
      end
      return @appointments_today
    end
  end

  # Returns a formatted String representation of the begin date of the appointment.
  def begin_date_nullsafe
    if begin_date?
      begin_date.strftime('%d.%m.%Y')
    else
      Date.today.strftime('%d.%m.%Y')
    end
  end

  # Validates the clear_group_employee_salutation
  def validate_conditional_employee_salutation
    if clear_group_employee_name.present? and clear_group_employee_salutation.empty?
      errors.add(:clear_group_employee_salutation, I18n.t('errors.messages.blank', attribute: :clear_group_employee_salutation))
    end
  end

  # Validates the clear_group_employee_name
  def validate_conditional_employee_name
    if clear_group_employee_salutation.present? and clear_group_employee_name.empty?
      errors.add(:clear_group_employee_name, I18n.t('errors.messages.blank', attribute: :clear_group_employee_name))
    end
  end

  # Returns +true+ if an +Appointment+ has a participating +employee+.
  def has_employee?
    clear_group_employee_salutation? and clear_group_employee_name?
  end

  # Returns a more readable salutation for the clear group employee
  def clear_group_employee_vocalized_salutation
    if clear_group_employee_salutation == "Herr"
      "Herrn"
    else
      clear_group_employee_salutation
    end
  end

  # Returns an +array+ of options for valid salutations.
  def options_for_salutation
    [
      ['Keine Auswahl', ''],
      ['Herr', 'Herr'],
      ['Frau', 'Frau'],
      ['Firma', 'Firma']
    ]
  end

  # Returns a formatted String which merges the +begin_date+ and the +begin_time+ of an +Appointment+.
  # The format is localized by the default locale.
  # See:
  # * +config/application.rb+ => +config.i18n.default_locale+
  #
  # ==== Example:
  #
  #   Freitag, 13. Juni 2014, 04:20 Uhr
  def formatted_begin
    formatted_date_time begin_date, begin_time
  end

  # Returns the merged appointment begin date and time.
  def merged_begin_date_time
    merge_date_time begin_date, begin_time
  end

  # Returns the merged appointment end date and time.
  def merged_end_date_time
    merge_date_time begin_date, begin_time + 60.minutes
  end

  # Returns a more human readable String representation of an +Appointment+.
  def to_s
    "Appointment:
    [begin_date: #{begin_date};
      begin_time: #{begin_time};
      external_participant_salutation: #{external_participant_salutation};
      external_participant_title: #{external_participant_title};
      external_participant_name: #{external_participant_name};
      external_participant_company: #{external_participant_company};
      clear_group_employee_salutation: #{clear_group_employee_salutation};
      clear_group_employee_name: #{clear_group_employee_name};
      created_at: #{created_at};
      updated_at: #{updated_at}]"
    end
  end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :showcase]
  before_filter :disable_nav, only: [:showcase]
  before_filter :update_date_params, only: [:create, :update]

  # GET /appointments/list
  def list
    @appointments = Appointment.all_desc.paginate(:page => params[:page], :per_page => 15)
  end

  # GET /appointments/showcase
  def showcase
    @appointments = Appointment.all_showcase
  end

  # GET /appointments/help
  def help
  end

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
    if params[:begin_date]
        begin_date = DateTime.parse(params[:begin_date])
        @appointment.begin_date = begin_date
        if params[:begin_date].include? "T"
          @appointment.begin_time = begin_date
        end
    end
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: t('.success') }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: t('.success') }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_list_url, notice: t('.success') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:begin_date, :begin_time, :end_time, :external_participant_salutation, :external_participant_title, :external_participant_name, :external_participant_company, :clear_group_employee_salutation, :clear_group_employee_name)
    end

    # Convert default values for the year month and day field of a time object on appointment creation.
    def update_date_params
      if params[:appointment]
        begin_date = DateTime.strptime(params[:appointment][:begin_date], "%d.%m.%Y")
        params[:appointment]['begin_time(1i)'] = begin_date.year.to_s
        params[:appointment]['begin_time(2i)'] = begin_date.month.to_s
        params[:appointment]['begin_time(3i)'] = begin_date.mday.to_s
      end
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_appointments.html.erb
<div class="panel panel-default">
  <div class="panel-heading"> 
    <h1>Termine</h1>
  </div> <!-- /.panel-heading --> 

  <div class="panel-body">
    <table>
      <thead>
        <tr>
          <th>Begin date</th>
          <th>End date</th>
          <th>External participant salutation</th>
          <th>External participant name</th>
          <th>External participant company</th>
          <th>Clear group employee salutation</th>
          <th>Clear group employee name</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @appointments.each do |appointment| %>
          <tr>
            <td><%= appointment.begin_date %></td>
            <td><%= appointment.end_date %></td>
            <td><%= appointment.external_participant_salutation %></td>
            <td><%= appointment.external_participant_name %></td>
            <td><%= appointment.external_participant_company %></td>
            <td><%= appointment.clear_group_employee_salutation %></td>
            <td><%= appointment.clear_group_employee_name %></td>
            <td><%= link_to 'Anzeigen', appointment %></td>
            <td><%= link_to 'Bearbeiten', edit_appointment_path(appointment) %></td>
            <td><%= link_to 'Löschen', appointment, method: :delete, data: { confirm: 'Bist Du sicher?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="panel-footer">
    <%= link_to 'Neuer Termin', new_appointment_path %>
  </div> <!-- /.panel-footer -->
</div> <!-- /.panel panel-default -->

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
<% if @appointment.errors.any? %>
<div id="error_explanation">
  <h2><%= t('errors.template.header', model: t('activerecord.models.appointment'), count: @appointment.errors.count) %></h2>
  <ul>
    <% @appointment.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="form-group">
  <div class="row">
    <div class="col-xs-4 col-md-4">
      <%= f.label :begin_date, t('.begin_date') %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4 col-md-4">
      <div class="input-group date">
        <%= f.text_field :begin_date, value: @appointment.begin_date_nullsafe, class: "form-control" %>
        <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
      </div>
    </div>
  </div>
</div>
<div class="form-group">
  <div class="row">
    <div class="col-xs-4 col-md-4">
      <%= f.label :begin_time, t('.begin_time') %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4 col-md-4">
      <%= f.time_select :begin_time, { minute_step: 15 }, { 'data-width' => "47.93%", class: "selectpicker" } %>
    </div>

  </div>
</div>
<div class="form-group">
  <div class="row">
    <div class="col-xs-4 col-md-4">
      <%= f.label :external_participant_salutation, t('.external_participant_salutation') %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4 col-md-4">
      <%= f.select( :external_participant_salutation, @appointment.options_for_salutation, { }, { 'data-width' => "100%", :class => "selectpicker"} ) %>
    </div>
  </div>
</div>
<div class="form-group">
  <%= f.label :external_participant_title, t('.external_participant_title') %>
  <%= f.text_field :external_participant_title, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :external_participant_name, t('.external_participant_name') %>
  <%= f.text_field :external_participant_name, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :external_participant_company, t('.external_participant_company') %>
  <%= f.text_field :external_participant_company, class: "form-control" %>
</div>
<div class="form-group">
  <div class="row">
    <div class="col-xs-4 col-md-4">
      <%= f.label :clear_group_employee_salutation, t('.clear_group_employee_salutation') %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4 col-md-4">
      <%= f.select( :clear_group_employee_salutation, @appointment.options_for_salutation, { }, { 'data-width' => "100%", :class => "selectpicker"} ) %>
    </div>
  </div>
</div>
<div class="form-group">
  <%= f.label :clear_group_employee_name, t('.clear_group_employee_name') %>
  <%= f.text_field :clear_group_employee_name, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.submit t('.submit'), class: "btn btn-primary" %>
</div>
<% end %>

app/views/appointments/_help_appointments.html.erb
<h3>Termine<a name="appointments"></a></h3>
<p>
  In der Termin&uuml;bersicht werden alle vorhandenen Termine aufgelistet. Die Sortierung erfolgt absteigend nach Datum, sodass die neusten Termine am Beginn stehen. Angezeigt werden die wichtigesten Daten zu einem Termin. Am rechten Rand kann man zur <a href="#view_appointment">Terminanzeige</a> oder <a href="#edit_appointment">Terminbearbeitung</a> wechseln oder den Termin l&ouml;schen. Unter der Tabelle befindet sich ein Link zum Wechsel zur Terminanlage.
</p>
</br>
<figure>
  <%= image_tag("../images/appointments.png", class: "img-responsive") %>
  <figcaption>Eine &Uuml;bersicht &uuml;ber alle Termine</figcaption>
</figure>

app/views/appointments/_help_calendar.html.erb
<h3>Kalenderansicht<a name="calendar"></a></h3>
<p>
  Die Kalenderansicht bietet drei verschiedene Ansichten: Die Monatsansicht, die Wochenansicht und die Tagesansicht. Zwischen diesen Ansichten kann mittels der Buttons am oberen rechten Rand umgeschalten werden. Am linken oberen Rand befinden sich Buttons mit einfachen Pfeilen um, je nach aktueller Ansicht einen Monat, eine Woche oder einen Tag zur&uuml; bzw. vor zu wechseln. Daneben befinden sich Buttons mit doppelten Pfeilen um ein Jahr zur&uuml;ck bzw. vor zu schalten. &Uuml;ber den Button "Heute" kann man direkt zum heutigen Tag wechseln. Der heutige Tag wird in der Kalenderansicht farblich hervorgehoben.
</p>
<p>
  Klickt man auf ein Feld im Kalender wird man zur <a href="#edit_appointment">Terminanlage</a> weitergeleitet. Dabei wird das Datum bereits &uuml;bernommen. Zus&auml;tzlich werden bei der Wochen- und Tagesansicht ebenso die Uhrzeit &uuml;bernommen.
</p>
</br>
<figure>
  <%= image_tag("../images/calendar.png", class: "img-responsive") %>
  <figcaption>Die Kalenderansicht mit unterschiedlichen Darstellungsm&ouml;glichkeiten</figcaption>
</figure>
</br>
<p>
  Sobald man sich mit der Maus &uuml;ber einen Termin bewegt, &ouml;ffnet sich ein Tooltip mit den wichtigsten Infos zum Termin. &Uuml;ber einen Klick auf den Termin kommt man zur <a href="#edit_appointment">Terminbearbeitung</a>.
</p>
</br>
<figure>
  <%= image_tag("../images/tooltip.png") %>
  <figcaption>Ein Tooltip mit den wichtigsten Informationen zum Termin</figcaption>
</figure>

app/views/appointments/_help_edit_appointment.html.erb
<h3>Termin anlegen/bearbeiten<a name="edit_appointment"></a></h3>
<p>
  Für Termin anlegen und bearbeiten gelten die gleichen Voraussetzungen, daher wird dies in einem Punkt beschrieben. Auf der Maske gibt es die folgenden Felder:
</p>
</br>
<figure>
  <%= image_tag("../images/edit-appointment.png", class: "img-responsive") %>
  <figcaption>Die Maske um einen neuen Termin anzulegen oder einen bereits bestehenden Termin abzuändern</figcaption>
</figure>
</br>
<table class="table">
  <thead>
    <tr>
      <th>Feld</th>
      <th>Beschreibung</th>
      <th>Plausi</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Datum</td>
      <td>Ein DatePicker-Feld mit dem das Datum für den Termin ausgewählt werden kann.</td>
      <td>Pflichtfeld</td>
    </tr>
    <tr>
      <td>Uhrzeit</td>
      <td>Das Feld Uhrzeit besteht aus zwei Auswahlfeldern, eines für die Stunden (00 bis 23) und eines für die Minuten (00, 15, 30 und 45)</td>
      <td>Pflichtfeld</td>
    </tr>
    <tr>
      <td>Teilnehmer Anrede</td>
      <td>Ein Auswahlfeld mit Herr und Frau</td>
      <td>Pflichtfeld</td>
    </tr>
    <tr>
      <td>Teilnehmer Titel</td>
      <td>In dieses Feld kann der Titel des Teilnehmers eingetragen werden, z.B. Dr. Prof.</td>
      <td>Darf nicht länger als 10 Zeichen sein</td>
    </tr>
    <tr>
      <td>Teilnehmer Name</td>
      <td>Der Nachname des Teilnehmers</td>
      <td>Pflichtfeld und darf nicht länger als 50 Zeichen sein</td>
    </tr>
    <tr>
      <td>Teilnehmer Firma</td>
      <td>Die Firma des Teilnehmers</td>
      <td>Darf nicht länger als 50 Zeichen sein</td>
    </tr>
    <tr>
      <td>Clear Group Mitarbieter Anrede</td>
      <td>Ein Auswahlfeld mit Herr und Frau</td>
      <td></td>
    </tr>
    <tr>
      <td>Clear Group Mitarbieter Name</td>
      <td>Der Nachname des Clear Group Mitarbeiters</td>
      <td>Darf nicht länger als 50 Zeichen sein</td>
    </tr>
  </tbody>
</table>
<p>
  In das Feld "Datum" kann man händisch ein gewünschtes Datum eintragen, oder die Funktionalität des DatePickers nutzen. Dazu betätigt man den Knopf ganz rechts im Datumsfeld. Es öffnet sich ein eigener kleiner Kalender über den man nun das Datum wählen kann. Das heutige Datum wird immer orange hervorgehoben, das ausgewählte Datum blau. Man kann über die Schaltflächen oben links und rechts jeweils einen Monat vor oder zurück blättern. Über die Schaltfläche "Heute" ganz unten kann man direkt zum heutigen Tag navigieren.
</p>
</br>
<figure>
  <%= image_tag("../images/datepicker.png", class: "img-responsive") %>
  <figcaption>Die Auswahl des Datum funktioniert komfortabel über einen kleinen Kalender.</figcaption>
</figure>
</br>
<p>
  Wie sie der oberen Tabelle entnehmen können gibt es für einige Felder Voraussetzungen die zum erfolgreichen speichern erfüllt werden müssen. Die Aussage Pflichfeld bedeutet, dass das Feld immer ausgefüllt werden muss. Eine Sonderheit gibt es zu den Prüfungen in der Tabelle. Die Felder "Clear Group Mitarbieter Anrede" und "Clear Group Mitarbieter Name" sind voneinander abhängig. Man muss in diese Felder nichts eintragen, aber sobald eines der beiden Felder gefüllt ist, muss das andere auch gefüllt werden.
</p>
<p>
  Haben Sie alle Felder ausgefüllt so drücken Sie auf den Button "Speichern". Sollten nun Fehler aufgetreten sein, werden Ihnen diese oben in der Maske ausgegeben und Sie müssen Ihre Daten nochmals überarbeiten.
</p>
</br>
<figure>
  <%= image_tag("../images/error.png", class: "img-responsive") %>
  <figcaption>Fehler beim Speichern</figcaption>
</figure>
</br>
<p>
  Konnten Sie Ihren Termin korrekt speichern, so werden Ihnen die <a href="#view_appointment">Termindetails</a> angezeigt.
</p>

app/views/appointments/_help_menu.html.erb
<h3>Men&uuml;leiste<a name="menu"></a></h3>
<p>
  Wenn Sie angemeldet sind, zeigt sich am oberen Rand der Anwendung die Men&uuml;leiste, durch welche Sie zu den verschiedenen Teilfunktionen navigieren k&ouml;nnen. Von links nach rechts k&ouml;nnen Sie:
  <ul>
    <li>&Uuml;ber das CLEAR GROUP Logo die <a href="#preview">Vorschau</a> der aktuellen Anzeige &ouml;ffnen</li>
    <li>Die <a href="#calendar">Kalenderansicht</a> &ouml;ffnen</li>
    <li>Die <a href="#appointments">Terminliste</a> &ouml;ffnen</li>
    <li>Einen <a href="#edit_appointment">neuen Termin</a> anlegen</li>
    <li>Die Hilfe aufrufen</li>
    <li>Sich abmelden</li>
  </ul>
</p>
</br>
<figure>
  <%= image_tag("../images/menu.png", class: "img-responsive") %>
  <figcaption>Die Men&uuml;leiste</figcaption>
</figure>

app/views/appointments/_help_start_sign_in.html.erb
<h3>Start und Anmeldung<a name="start_sign_in"></a></h3>
<p>
  Der CLEAR GROUP Welcome Screen ist eine Webanwendung zur Verwaltung von Terminen und Begr&uuml;&szlig;ung der Terminteilnehmer auf einem Willkommensbildschirm. &Uuml;ber die Adresse <a href="http://192.168.15.180">"192.168.15.180"</a> kann die Anwendung in einem Browser (Bestenfalls Google Chrome oder Mozilla Firefox) aufgerufen werden. Um nun die Termine verwalten zu k&ouml;nnen, muss man sich zun&auml;chst &uuml;ber die Startmaske anmelden. Zur Anmeldung wird eine E-Mail Adresse und ein Passwort ben&ouml;tigt. Hierbei gibt es bereits folgende vorhandene Benutzerdaten:
  <table class="table">
    <thead>
      <tr>
        <th>E-Mail</th>
        <th>Passwort</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>welcome@clear-group.de</td>
        <td>welcome2clear</td>
      </tr>
      <tr>
        <td>admin@clear-group.de</td>
        <td>admin@welcome</td>
      </tr>
    </tbody>
  </table>
</p>
</br>
<figure>
  <%= image_tag("../images/sign-in.png", class: "img-responsive") %>
  <figcaption>Die Anmeldung</figcaption>
</figure>

app/views/appointments/_help_view_appointment.html.erb
<h3>Termindetails<a name="view_appointment"></a></h3>
<p>
  In den Termindetails finden Sie alle Informationen zu einem Termin. Auch hier finden Sie die selben Aktionen wie in der <a href="#appointments">Terminliste</a>.
</p>
</br>
<figure>
  <%= image_tag("../images/view-appointment.png", class: "img-responsive") %>
  <figcaption>Anzeige aller Informationen zu einem Termin</figcaption>
</figure>

app/views/appointments/_listing.html.erb
<div class="panel panel-default">
  <div class="panel-heading"> 
    <h2>Termine</h2>
  </div> <!-- /.panel-heading --> 

  <div class="panel-body">
    <table class="table">
      <thead>
        <tr>
          <th>Termin Beginn</th>
          <th>Termin Ende</th>
          <th>Teilnehmer Name</th>
          <th>Teilnehmer Firma</th>
          <th>Clear Group Mitarbeiter Name</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @appointments.each do |appointment| %>
          <tr>
            <td><%= appointment.formatted_begin %></td>
            <td><%= appointment.formatted_end %></td>
            <td><%= appointment.external_participant_salutation %> <%= appointment.external_participant_title %> <%= appointment.external_participant_name %></td>
            <td><%= appointment.external_participant_company %></td>
            <td><%= appointment.clear_group_employee_salutation %> <%= appointment.clear_group_employee_name %></td>
            <td><%= link_to 'Anzeigen', appointment %></td>
            <td><%= link_to 'Bearbeiten', edit_appointment_path(appointment) %></td>
            <td><%= link_to 'Löschen', appointment, method: :delete, data: { confirm: 'Wollen Sie den Termin wirklich löschen?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div> <!-- /.panel-body -->

  <div class="panel-footer">
    <%= link_to 'Neuer Termin', new_appointment_path %>
  </div> <!-- /.panel-footer -->
</div> <!-- /.panel panel-default -->

app/views/appointments/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h2><%= t('.heading') %></h2>
  </div> <!-- /.panel-heading -->

  <div class="panel-body">
    <%= render 'form' %>
  </div> <!-- /.panel-body -->

  <div class="panel-footer">
    <%= link_to t('.show'), @appointment %> |
    <%= link_to t('.destroy'), @appointment, method: :delete, data: { confirm: t('.confirm') } %> |
    <%= link_to t('.back'), :back %>
  </div> <!-- /.panel-footer -->
</div> <!-- /.panel panel-default -->

app/views/appointments/index.html.erb
<% if user_signed_in? %>
  <%= render 'appointments/calendar' %>
<% else %>
  <%= render 'appointments/showcase' %>
<% end %>

app/views/appointments/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h2><%= t('.heading') %></h2>
  </div> <!-- /.panel-heading -->

  <div class="panel-body">
    <div class="row">
      <div class="col-xs-6 col-md-3">
        <strong><%= t('.appointment_begin') %>:</strong>
      </div>
      <div class="col-xs-6 col-md-9">
        <%= @appointment.formatted_begin %>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-6 col-md-3">
        <strong><%= t('.external_participant') %>:</strong>
      </div>
      <div class="col-xs-6 col-md-9">
        <%= @appointment.external_participant_salutation %> <%= @appointment.external_participant_title %> <%= @appointment.external_participant_name %><% if @appointment.external_participant_company? %>, <%= @appointment.external_participant_company %><% end %>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-6 col-md-3">
        <strong><%= t('.clear_group_employee') %>:</strong>
      </div>
      <div class="col-xs-6 col-md-9">
        <%= @appointment.clear_group_employee_salutation %> <%= @appointment.clear_group_employee_name %>
      </div>
    </div>
   </div> <!-- /.panel-body -->

   <div class="panel-footer">
     <%= link_to t('.edit'), edit_appointment_path(@appointment) %> |
     <%= link_to t('.destroy'), @appointment, method: :delete, data: { confirm: t('.confirm') } %> |
     <%= link_to t('.back'), :back %>
   </div> <!-- /.panel-footer -->
 </div> <!-- /.panel panel-default -->