config/routes.rb
Rails.application.routes.draw do
  resources :slides

  get 'appointments/list'
  get 'appointments/showcase'
  get 'appointments/help'
  resources :appointments

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'appointments#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("../images/logo-navbar-new.png", class: "navbar-brand-image"), appointments_showcase_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% unless user_signed_in? %>
          <li>
            <%= link_to new_user_session_path do %>
              <span class="glyphicon glyphicon-log-in"></span> <%= t('.sign_in') %>
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to appointments_path do %>
               <span class="glyphicon glyphicon-calendar"></span> <%= t('.calendar') %>
            <% end %>
          </li>
          <li>
            <%= link_to appointments_list_path do %>
               <span class="glyphicon glyphicon-list"></span> <%= t('.appointments') %>
            <% end %>
          </li>
          <li>
            <%= link_to new_appointment_path do %>
              <span class="glyphicon glyphicon-plus"></span> <%= t('.new_appointment') %>
            <% end %>
          </li>
          <li>
            <%= link_to slides_path do %>
               <span class="glyphicon glyphicon-picture"></span> <%= t('.slides') %>
            <% end %>
          </li>
          <li>
            <%= link_to new_slide_path do %>
              <span class="glyphicon glyphicon-cloud-upload"></span> <%= t('.new_slide') %>
            <% end %>
          </li>
          <li>
            <%= link_to appointments_help_path do %>
              <span class="glyphicon glyphicon-info-sign"></span> <%= t('.help') %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <span class="glyphicon glyphicon-log-out"></span> <%= t('.sign_out') %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="de">
<head>
  <title><%= t('.title') %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <%= render 'layouts/header' unless @disable_nav %>
  <div class="container">
    <% flash.each do | name, msg | %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>